server:
  port: 7001

eureka:
  instance:
    #hostname: localhost #eureka服务端的实例名称
    #集群后eureka实例名称不能重复
    hostname: eureka7001.com
  client:
    #false表示不向往注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #eureka集群，相互注册，互相守望
      defaultZone: http://eureka7002.com:7002/eureka/ #修改映射配置文件 -》 C:\Windows\System32\drivers\etc\hosts，避免服务重名
  server:
    #关闭自我保护机制，保证不可用服务被及时删除（默认为true，开启自我保护机制）
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000 #时间间隔
