server:
  port: 83

spring:
  application:
    name: cloud-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

service-url:
  nacos-user-service: http://cloud-payment-provider